format = """
$username\
$directory\
$git_branch\
$git_status\
$python\
$character"""

[username]
style_user = 'fg:#ca9ee6 bold'
style_root = 'fg:#e78284 bold'
format = '[$user]($style)'
disabled = false
show_always = true

[directory]
style = "fg:#8caaee bold"
format = " in [$path]($style)"
truncation_length = 8
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "Documents 󰈙"
"Downloads" = "Downloads "
"Pictures" = "Pictures "

[python]
symbol = " "
style = "fg:#e5c890"
format = ' \[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[git_branch]
symbol = ""
style = "fg:#a6da95 bold"
format = ' on[ $symbol $branch ]($style)'

[git_status]
style = "fg:#ea999c"
format = "[$all_status$ahead_behind]($style)"
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[character]
success_symbol = "[❯](#babbf1)"
error_symbol = "[❯](#e78284)"