[general]
temp-day=6500
temp-night=4800
fade=1

brightness-day=1.0
brightness-night=0.2

;dawn-time=08:00
;dusk-time=18:00

; Location provider (geoclue2 for automatic, manual for fixed)
location-provider=manual
adjustment-method=wayland

[manual]
lat=53.24
lon=14.29
